# Copy this file in the same location and name it application.yml
# Changes are most likely necessary for the datasource parameters and the botRefactoringDirectory
spring:
  application:
    name: refactoringbottrainer
  profiles:
    active: "dev"
server:
  port: ${SERVER_PORT:8809}
---
spring:
  profiles: dev
wit:
  witClientToken: V2FLDGUZHWA3X7WYL5XLWORJTCB34I6R